recipe = 'eos'

template = 'template.in'

[cli.mpi]
np = 112

[trial_eos]
type = 'bm3'
values = ['300.44 bohr^3', '74.88 GPa', 4.82]

[fixed.pressures]
unit = 'GPa'
values = [-5, -2, 0, 5, 10, 15, 17, 20]

[save]
status = 'status.jls'
